# Generated by Django 5.1.2 on 2024-12-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('b_num', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('write_time', models.DateTimeField(auto_now=True)),
                ('v_num', models.IntegerField(default=0)),
                ('g_num', models.IntegerField(default=0)),
                ('d_check', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'board',
            },
        ),
    ]
